### ISSUE TITLE
Linux/Mac build support

### ISSUE THREAD

**Issue by api-Hypernova** [chasester/Rival3dengine#8]
Should be able to build the source on Linux and Mac using Make or Cmake.

**Comment by chasester** [comment]
You should the file system should be the same as the one I shipped you. As noted on tesseract web page the source/extralib/angel/source directory is gone cuz i'm using git submodules and the source file was a later add on. I will move any modified cpp and h files to the source files (most likely engine). This is where the new home will be. Then the ones i did not modify I will point to their original location inside of angelscripts submodule. With this in mind, serializer.h,cpp halo.h wings.cpp should be the only ones with modification at this point. Though I may have to move all the said files because there may have minor errors in the code because they are using std::string and std::vector not cubes string or vectors. Though I did change chubes char [256] define from the typename string to the type name cubestr and added a typename that change str to std::string. It May still need to add str:: in front of all said classes because they declare using std which clashes with ::vector :( 

All this to say NO not really. Also the name bullet3-master been changed to bullet3. But all other code and linking remains the same, So just adding that one angel/source into the engine folder and renaming the call for bullet3 should fix everything. I will be doing this stuff tonight and should reflect in the repo. I will do a dry run and build from the repo to guarantee no error, but will probably work on an offline version cuz if git is like svn, you can screw shit up easily and its good to have a backup to merge from.

If you could also leave any project files on the root in  the source folder (source/COMPILERNAME_VERSION)  this way people can just build with no problems. Also build and leave the *.lib files and link in bullet and angelscript files all into the same project file so they can all be built into libs (or linux and mac equivalent) that would be awesome. Ease of use is my main concern.
